### ISSUE TITLE
Django 1.8.3 ValueError: Invalid column index 0

### ISSUE THREAD

**Issue by paridin** [goinnn/django-tables2-reports#29]
After doing the changes for work with django-tables2-reports, I try to export to excel but i got a ValueError: Invalid column index 0, Otherwise If export to CVS it works fine

i'm using openpyxl

Here is my traceback
https://gist.github.com/anonymous/47efa2aa3751f92b26d8

**Comment by chriswyatt** [comment]
I came across this problem too. Version 2.0.0 introduced a backwards-incompatible change. You need to use version 1.8.6.

**Comment by paridin** [comment]
Thanks, before you told me, I tried xlwt 1.0.0 and it works fine too, Actually nobody depends of the openpyxl, I chose openpyxl because in the past I worked with it.

**Comment by mpasternak** [comment]
Fixed, thanks for the report. Openpyxl >2 supported.
