### ISSUE TITLE
support for recently changes to get_table_pagination

### ISSUE THREAD

**Issue by smason** [goinnn/django-tables2-reports#34]
Recently, bradleyayers/django-tables2#320 changed the API for `get_table_pagination` to include a parameter for the table (to reflect changes to support the multi table implementation)

[Line 34 of `django_tables2_reports/views.py`](https://github.com/goinnn/django-tables2-reports/blob/67e4c595518fded374f6151147334ad457b1af27/django_tables2_reports/views.py#L34) needs to trivially change in response

I can submit a pull request, but would obviously break when trying to use an older version of `django-tables2`

**Comment by fkdeboer** [comment]
It seems there's not much activity here anymore.
 I would be in favour of updating this extension to the renewed django-tables2

**Comment by mpasternak** [comment]
Updated. Thanks for the report.
