### ISSUE TITLE
Add support for formatting xlwt cell background color style

### ISSUE THREAD

**Issue by samaust** [goinnn/django-tables2-reports#35]
This is a suggestion for an improvement. I'd like the xls format output to set the cell background color when using xlwt.

I forked the project and made a solution that works for my needs. I'm not going to post a PR since I don't think it's a good enough solution for widespread use and I only changed the code related to xlwt so it will break with the other xls libraries.

Here's my branch with my solution :
[https://github.com/samaust/django-tables2-reports/tree/xlwt_background-color](https://github.com/samaust/django-tables2-reports/tree/xlwt_background-color)

When creating my table, I pass additional columns that contain hex color codes. Those column are set to not show up on the table. If I have a column called "columnname", I also add another column called "columnname_color". My branch searches for those color columns and adds the colors to the custom Excel palette.

**Comment by mpasternak** [comment]
Cool idea. I think that styling cell background depending on the data inside the cells belongs probably more to Django-tables2 and not necessarily here. Also, as you pointed out, you don't support other backends. I'm closing this issue thanks.
