### ISSUE TITLE
Issue in template columns

### ISSUE THREAD

**Issue by mkalioby** [goinnn/django-tables2-reports#36]
Template columns doesn't respect the request.session, django-tables2 respects them so the template working under django-tables2 doesn't work under django-tables2-reports

**Comment by samaust** [comment]
Could you give more details :
1. python, django, django-tables2 and django-tables2-reports versions
2. Could you explain the issue in more detail ? What exactly does not work when request.session is not respected ?
3. Can you share a code sample to reproduce the issue ?

**Comment by mpasternak** [comment]
Please provide a minimal non working code example and reopen. Thanks!

**Comment by mkalioby** [comment]
[DjangoReports2issue.zip](https://github.com/goinnn/django-tables2-reports/files/1088750/DjangoReports2issue.zip)

Here you go, sorry for the delay.
