### ISSUE TITLE
VERSION issue

### ISSUE THREAD

**Issue by jacopsd** [goinnn/django-tables2-reports#40]
Python 2.7.10
Django 1.8.16

Code below gives  issue:

return ".".join(VERSION)
TypeError: sequence item 0: expected string, int found

Code: __init__.py:
    VERSION = (0, 1, 0)
    def get_version():
        return ".".join(VERSION)

**Comment by mpasternak** [comment]
You're right. This code sucks. Please submit a pull request.

**Comment by jacopsd** [comment]
The test project doesn't start:

According to the instructions, after pip install -r requirements.txt
    python manage.py syncdb --noinput
    python manage.py runserver

....
....

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_tables2_reports

I assume the search path needs to be set upfront or is something else wrong here?

**Comment by mpasternak** [comment]
Commited, thanks.
