### ISSUE TITLE
ValueError when text in column is too long

### ISSUE THREAD

**Issue by taialex1** [goinnn/django-tables2-reports#43]
When creating a xls report and the the text inside one of the cell in the table is too long, you get a ValueError because _column width (602112) not an int in range(65536)_.

The function _get_xls_col_width_ in the _xlwt_converter_ must not return a value higher than 65535. The _set_width_ method of the _Column_ class of _xlwt_ will raise the ValueError.

A possible fix to this would be to return the min value between the current approximation, and the max value allowed by _xlwt_.

**Comment by mpasternak** [comment]
Patches accepted, feel free to submit a pull request.

**Comment by mpasternak** [comment]
Closing as no response from reporter. Also, dt2r is retired in favour of dt2 (see recent README.md)
